import { describe, expect, it } from "vitest";
import { DomainValidationError } from "../../../src/domain/domain-validation-error.js";
import { reconstituteReconciliationAction } from "../../../src/reconciliation/domain/reconciliation-action.js";
import { targetStatusForAction, type ReconciliationActionType, type ReconciliationFindingStatus } from "../../../src/reconciliation/domain/reconciliation-vocabulary.js";

describe("Reconciliation lifecycle", () => {
  it.each<[ReconciliationFindingStatus, ReconciliationActionType, ReconciliationFindingStatus]>([["open", "acknowledge", "acknowledged"], ["open", "resolve", "resolved"], ["open", "ignore", "ignored"], ["acknowledged", "resolve", "resolved"], ["acknowledged", "ignore", "ignored"]])("allows %s --%s--> %s", (from, action, to) => expect(targetStatusForAction(from, action)).toBe(to));
  it.each<[ReconciliationFindingStatus, ReconciliationActionType]>([["acknowledged", "acknowledge"], ["resolved", "resolve"], ["resolved", "ignore"], ["ignored", "resolve"], ["ignored", "ignore"]])("rejects %s --%s", (from, action) => expect(() => targetStatusForAction(from, action)).toThrowError(DomainValidationError));
  it("reconstitutes an immutable operator action", () => { const at = new Date("2026-09-01T12:00:00Z"); const action = reconstituteReconciliationAction({ id: 1, findingId: 2, actionType: "resolve", fromStatus: "open", toStatus: "resolved", actorType: "operator", actorId: "demo-operator", reason: "Evidence verified", idempotencyKey: "action-1", requestFingerprint: "a".repeat(64), occurredAt: at, recordedAt: at }); expect(action).toMatchObject({ toStatus: "resolved", actorType: "operator" }); expect(Object.isFrozen(action)).toBe(true); });
  it("rejects blank actor/reason and an incoherent transition", () => { const at = new Date(); const base = { id: 1, findingId: 2, actionType: "resolve" as const, fromStatus: "open" as const, toStatus: "resolved" as const, actorType: "operator", actorId: "operator", reason: "reason", idempotencyKey: "key", requestFingerprint: "a".repeat(64), occurredAt: at, recordedAt: at }; expect(() => reconstituteReconciliationAction({ ...base, actorId: " " })).toThrowError(DomainValidationError); expect(() => reconstituteReconciliationAction({ ...base, reason: " " })).toThrowError(DomainValidationError); expect(() => reconstituteReconciliationAction({ ...base, toStatus: "ignored" })).toThrowError(DomainValidationError); });
});
