CREATE TABLE "customers" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "customers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"display_name" text NOT NULL,
	"created_at" timestamp (3) with time zone NOT NULL,
	CONSTRAINT "customers_display_name_not_blank" CHECK (length(btrim("customers"."display_name")) > 0)
);
--> statement-breakpoint
CREATE TABLE "idempotency_records" (
	"command_type" varchar(32) NOT NULL,
	"idempotency_key" varchar(128) NOT NULL,
	"request_fingerprint" varchar(64) NOT NULL,
	"resource_id" integer NOT NULL,
	"created_at" timestamp (3) with time zone NOT NULL,
	CONSTRAINT "idempotency_records_command_type_idempotency_key_pk" PRIMARY KEY("command_type","idempotency_key"),
	CONSTRAINT "idempotency_records_command_type_allowed" CHECK ("idempotency_records"."command_type" in ('create_customer', 'create_contract')),
	CONSTRAINT "idempotency_records_key_format" CHECK ("idempotency_records"."idempotency_key" ~ '^[!-~]{1,128}$'),
	CONSTRAINT "idempotency_records_fingerprint_format" CHECK ("idempotency_records"."request_fingerprint" ~ '^[0-9a-f]{64}$'),
	CONSTRAINT "idempotency_records_resource_id_positive" CHECK ("idempotency_records"."resource_id" > 0)
);
