CREATE TABLE "contracts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "contracts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"customer_id" integer NOT NULL,
	"total_amount_cents" bigint NOT NULL,
	"currency" varchar(3) NOT NULL,
	"installment_count" integer NOT NULL,
	"first_due_date" date NOT NULL,
	"status" varchar(16) NOT NULL,
	"created_at" timestamp (3) with time zone NOT NULL,
	CONSTRAINT "contracts_total_amount_positive" CHECK ("contracts"."total_amount_cents" > 0),
	CONSTRAINT "contracts_total_amount_safe_integer" CHECK ("contracts"."total_amount_cents" <= 9007199254740991),
	CONSTRAINT "contracts_currency_eur" CHECK ("contracts"."currency" = 'EUR'),
	CONSTRAINT "contracts_installment_count_positive" CHECK ("contracts"."installment_count" > 0),
	CONSTRAINT "contracts_installment_count_within_total" CHECK ("contracts"."installment_count" <= "contracts"."total_amount_cents"),
	CONSTRAINT "contracts_status_active" CHECK ("contracts"."status" = 'active')
);
--> statement-breakpoint
CREATE TABLE "installments" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "installments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"contract_id" integer NOT NULL,
	"position" integer NOT NULL,
	"amount_cents" bigint NOT NULL,
	"due_date" date NOT NULL,
	"status" varchar(16) NOT NULL,
	"created_at" timestamp (3) with time zone NOT NULL,
	CONSTRAINT "installments_contract_id_position_unique" UNIQUE("contract_id","position"),
	CONSTRAINT "installments_position_positive" CHECK ("installments"."position" > 0),
	CONSTRAINT "installments_amount_positive" CHECK ("installments"."amount_cents" > 0),
	CONSTRAINT "installments_amount_safe_integer" CHECK ("installments"."amount_cents" <= 9007199254740991),
	CONSTRAINT "installments_status_pending" CHECK ("installments"."status" = 'pending')
);
--> statement-breakpoint
ALTER TABLE "contracts" ADD CONSTRAINT "contracts_customer_id_customers_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customers"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "installments" ADD CONSTRAINT "installments_contract_id_contracts_id_fk" FOREIGN KEY ("contract_id") REFERENCES "public"."contracts"("id") ON DELETE no action ON UPDATE no action;