CREATE TABLE "payment_allocations" (
	"payment_id" integer NOT NULL,
	"installment_id" integer NOT NULL,
	"contract_id" integer NOT NULL,
	"amount_cents" bigint NOT NULL,
	CONSTRAINT "payment_allocations_payment_id_installment_id_pk" PRIMARY KEY("payment_id","installment_id"),
	CONSTRAINT "payment_allocations_amount_positive" CHECK ("payment_allocations"."amount_cents" > 0),
	CONSTRAINT "payment_allocations_amount_safe_integer" CHECK ("payment_allocations"."amount_cents" <= 9007199254740991)
);
--> statement-breakpoint
CREATE TABLE "payments" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "payments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"contract_id" integer NOT NULL,
	"amount_cents" bigint NOT NULL,
	"received_at" timestamp (3) with time zone NOT NULL,
	"created_at" timestamp (3) with time zone NOT NULL,
	CONSTRAINT "payments_id_contract_id_unique" UNIQUE("id","contract_id"),
	CONSTRAINT "payments_amount_positive" CHECK ("payments"."amount_cents" > 0),
	CONSTRAINT "payments_amount_safe_integer" CHECK ("payments"."amount_cents" <= 9007199254740991)
);
--> statement-breakpoint
ALTER TABLE "idempotency_records" DROP CONSTRAINT "idempotency_records_command_type_allowed";--> statement-breakpoint
ALTER TABLE "installments" DROP CONSTRAINT "installments_status_pending";--> statement-breakpoint
ALTER TABLE "installments" ADD CONSTRAINT "installments_id_contract_id_unique" UNIQUE("id","contract_id");--> statement-breakpoint
ALTER TABLE "payment_allocations" ADD CONSTRAINT "payment_allocations_payment_contract_fk" FOREIGN KEY ("payment_id","contract_id") REFERENCES "public"."payments"("id","contract_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "payment_allocations" ADD CONSTRAINT "payment_allocations_installment_contract_fk" FOREIGN KEY ("installment_id","contract_id") REFERENCES "public"."installments"("id","contract_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "payments" ADD CONSTRAINT "payments_contract_id_contracts_id_fk" FOREIGN KEY ("contract_id") REFERENCES "public"."contracts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "idempotency_records" ADD CONSTRAINT "idempotency_records_command_type_allowed" CHECK ("idempotency_records"."command_type" in ('create_customer', 'create_contract', 'record_payment'));--> statement-breakpoint
ALTER TABLE "installments" ADD CONSTRAINT "installments_status_allowed" CHECK ("installments"."status" in ('pending', 'partially_paid', 'paid'));
