CREATE TABLE "ledger_entries" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ledger_entries_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"payment_id" integer NOT NULL,
	"effect_type" varchar(32) NOT NULL,
	"amount_cents" bigint NOT NULL,
	"currency" varchar(3) NOT NULL,
	"event_at" timestamp (3) with time zone NOT NULL,
	"recorded_at" timestamp (3) with time zone NOT NULL,
	CONSTRAINT "ledger_entries_payment_id_unique" UNIQUE("payment_id"),
	CONSTRAINT "ledger_entries_effect_type_payment_recorded" CHECK ("ledger_entries"."effect_type" = 'payment_recorded'),
	CONSTRAINT "ledger_entries_amount_positive" CHECK ("ledger_entries"."amount_cents" > 0),
	CONSTRAINT "ledger_entries_amount_safe_integer" CHECK ("ledger_entries"."amount_cents" <= 9007199254740991),
	CONSTRAINT "ledger_entries_currency_eur" CHECK ("ledger_entries"."currency" = 'EUR')
);
--> statement-breakpoint
ALTER TABLE "ledger_entries" ADD CONSTRAINT "ledger_entries_payment_id_payments_id_fk" FOREIGN KEY ("payment_id") REFERENCES "public"."payments"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
INSERT INTO "ledger_entries" (
	"payment_id",
	"effect_type",
	"amount_cents",
	"currency",
	"event_at",
	"recorded_at"
)
SELECT
	"payments"."id",
	'payment_recorded',
	"payments"."amount_cents",
	"contracts"."currency",
	"payments"."received_at",
	"payments"."created_at"
FROM "payments"
INNER JOIN "contracts" ON "contracts"."id" = "payments"."contract_id";
--> statement-breakpoint
CREATE FUNCTION "prevent_ledger_entries_mutation"()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
	RAISE EXCEPTION 'ledger_entries is append-only';
END;
$$;
--> statement-breakpoint
CREATE TRIGGER "ledger_entries_append_only"
BEFORE UPDATE OR DELETE ON "ledger_entries"
FOR EACH STATEMENT
EXECUTE FUNCTION "prevent_ledger_entries_mutation"();
