CREATE TABLE "stripe_webhook_events" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stripe_webhook_events_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"stripe_event_id" varchar(255) NOT NULL,
	"event_type" varchar(64) NOT NULL,
	"stripe_payment_intent_id" varchar(255),
	"raw_payload" "bytea" NOT NULL,
	"received_at" timestamp (3) with time zone NOT NULL,
	"status" varchar(16) NOT NULL,
	"processing_token" uuid,
	"processing_started_at" timestamp (3) with time zone,
	"processed_at" timestamp (3) with time zone,
	"payment_id" integer,
	"last_error_code" varchar(64),
	CONSTRAINT "stripe_webhook_events_stripe_event_id_unique" UNIQUE("stripe_event_id"),
	CONSTRAINT "stripe_webhook_events_event_id_format" CHECK ("stripe_webhook_events"."stripe_event_id" ~ '^evt_[A-Za-z0-9]+$'),
	CONSTRAINT "stripe_webhook_events_event_type_supported" CHECK ("stripe_webhook_events"."event_type" = 'payment_intent.succeeded'),
	CONSTRAINT "stripe_webhook_events_payment_intent_id_format" CHECK ("stripe_webhook_events"."stripe_payment_intent_id" is null or "stripe_webhook_events"."stripe_payment_intent_id" ~ '^pi_[A-Za-z0-9]+$'),
	CONSTRAINT "stripe_webhook_events_raw_payload_size" CHECK (octet_length("stripe_webhook_events"."raw_payload") between 1 and 1048576),
	CONSTRAINT "stripe_webhook_events_status_supported" CHECK ("stripe_webhook_events"."status" in ('received', 'processing', 'processed', 'failed')),
	CONSTRAINT "stripe_webhook_events_state_consistency" CHECK ((
        ("stripe_webhook_events"."status" = 'received' and "stripe_webhook_events"."processing_token" is null and "stripe_webhook_events"."processing_started_at" is null and "stripe_webhook_events"."payment_id" is null and "stripe_webhook_events"."processed_at" is null and "stripe_webhook_events"."last_error_code" is null)
        or ("stripe_webhook_events"."status" = 'processing' and "stripe_webhook_events"."processing_token" is not null and "stripe_webhook_events"."processing_started_at" is not null and "stripe_webhook_events"."payment_id" is null and "stripe_webhook_events"."processed_at" is null and "stripe_webhook_events"."last_error_code" is null)
        or ("stripe_webhook_events"."status" = 'processed' and "stripe_webhook_events"."processing_token" is null and "stripe_webhook_events"."processing_started_at" is null and "stripe_webhook_events"."payment_id" is not null and "stripe_webhook_events"."processed_at" is not null and "stripe_webhook_events"."last_error_code" is null and "stripe_webhook_events"."stripe_payment_intent_id" is not null)
        or ("stripe_webhook_events"."status" = 'failed' and "stripe_webhook_events"."processing_token" is null and "stripe_webhook_events"."processing_started_at" is null and "stripe_webhook_events"."payment_id" is null and "stripe_webhook_events"."processed_at" is not null and "stripe_webhook_events"."last_error_code" is not null)
      ))
);
--> statement-breakpoint
ALTER TABLE "stripe_webhook_events" ADD CONSTRAINT "stripe_webhook_events_payment_id_payments_id_fk" FOREIGN KEY ("payment_id") REFERENCES "public"."payments"("id") ON DELETE no action ON UPDATE no action;
--> statement-breakpoint
CREATE FUNCTION protect_stripe_webhook_event_evidence()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
	IF TG_OP = 'DELETE' THEN
		RAISE EXCEPTION 'stripe_webhook_events evidence cannot be deleted';
	END IF;

	IF OLD.stripe_event_id IS DISTINCT FROM NEW.stripe_event_id
		OR OLD.event_type IS DISTINCT FROM NEW.event_type
		OR OLD.stripe_payment_intent_id IS DISTINCT FROM NEW.stripe_payment_intent_id
		OR OLD.raw_payload IS DISTINCT FROM NEW.raw_payload
		OR OLD.received_at IS DISTINCT FROM NEW.received_at THEN
		RAISE EXCEPTION 'stripe_webhook_events evidence cannot be changed';
	END IF;

	RETURN NEW;
END;
$$;
--> statement-breakpoint
CREATE TRIGGER stripe_webhook_events_protect_evidence
BEFORE UPDATE OR DELETE ON "stripe_webhook_events"
FOR EACH ROW
EXECUTE FUNCTION protect_stripe_webhook_event_evidence();
