CREATE TABLE "refund_allocations" (
	"refund_id" integer NOT NULL,
	"payment_id" integer NOT NULL,
	"installment_id" integer NOT NULL,
	"amount_cents" bigint NOT NULL,
	CONSTRAINT "refund_allocations_refund_id_installment_id_pk" PRIMARY KEY("refund_id","installment_id"),
	CONSTRAINT "refund_allocations_amount_positive" CHECK ("refund_allocations"."amount_cents" > 0),
	CONSTRAINT "refund_allocations_amount_safe_integer" CHECK ("refund_allocations"."amount_cents" <= 9007199254740991)
);
--> statement-breakpoint
CREATE TABLE "refunds" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "refunds_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"payment_id" integer NOT NULL,
	"amount_cents" bigint NOT NULL,
	"refunded_at" timestamp (3) with time zone NOT NULL,
	"created_at" timestamp (3) with time zone NOT NULL,
	CONSTRAINT "refunds_id_payment_id_unique" UNIQUE("id","payment_id"),
	CONSTRAINT "refunds_amount_positive" CHECK ("refunds"."amount_cents" > 0),
	CONSTRAINT "refunds_amount_safe_integer" CHECK ("refunds"."amount_cents" <= 9007199254740991)
);
--> statement-breakpoint
ALTER TABLE "idempotency_records" DROP CONSTRAINT "idempotency_records_command_type_allowed";--> statement-breakpoint
ALTER TABLE "ledger_entries" DROP CONSTRAINT "ledger_entries_effect_type_payment_recorded";--> statement-breakpoint
ALTER TABLE "ledger_entries" ALTER COLUMN "payment_id" DROP NOT NULL;--> statement-breakpoint
ALTER TABLE "ledger_entries" ADD COLUMN "refund_id" integer;--> statement-breakpoint
ALTER TABLE "refund_allocations" ADD CONSTRAINT "refund_allocations_refund_payment_fk" FOREIGN KEY ("refund_id","payment_id") REFERENCES "public"."refunds"("id","payment_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "refund_allocations" ADD CONSTRAINT "refund_allocations_payment_installment_fk" FOREIGN KEY ("payment_id","installment_id") REFERENCES "public"."payment_allocations"("payment_id","installment_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "refunds" ADD CONSTRAINT "refunds_payment_id_payments_id_fk" FOREIGN KEY ("payment_id") REFERENCES "public"."payments"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ledger_entries" ADD CONSTRAINT "ledger_entries_refund_id_refunds_id_fk" FOREIGN KEY ("refund_id") REFERENCES "public"."refunds"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "ledger_entries" ADD CONSTRAINT "ledger_entries_refund_id_unique" UNIQUE("refund_id");--> statement-breakpoint
ALTER TABLE "idempotency_records" ADD CONSTRAINT "idempotency_records_command_type_allowed" CHECK ("idempotency_records"."command_type" in ('create_customer', 'create_contract', 'record_payment', 'record_refund'));--> statement-breakpoint
ALTER TABLE "ledger_entries" ADD CONSTRAINT "ledger_entries_effect_type_allowed" CHECK ("ledger_entries"."effect_type" in ('payment_recorded', 'refund_recorded'));--> statement-breakpoint
ALTER TABLE "ledger_entries" ADD CONSTRAINT "ledger_entries_source_effect_consistent" CHECK ((
        ("ledger_entries"."effect_type" = 'payment_recorded' and "ledger_entries"."payment_id" is not null and "ledger_entries"."refund_id" is null)
        or ("ledger_entries"."effect_type" = 'refund_recorded' and "ledger_entries"."payment_id" is null and "ledger_entries"."refund_id" is not null)
      ));