CREATE TABLE "external_source_events" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "external_source_events_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"source" varchar(64) NOT NULL,
	"source_event_id" varchar(255) NOT NULL,
	"event_type" varchar(32) NOT NULL,
	"amount_cents" bigint NOT NULL,
	"currency" varchar(3) NOT NULL,
	"occurred_at" timestamp (3) with time zone NOT NULL,
	"received_at" timestamp (3) with time zone NOT NULL,
	"external_reference" varchar(255) NOT NULL,
	"internal_payment_id" integer,
	"internal_refund_id" integer,
	"provider_payment_reference" varchar(255),
	"raw_payload" "bytea" NOT NULL,
	"metadata" jsonb NOT NULL,
	"created_at" timestamp (3) with time zone NOT NULL,
	CONSTRAINT "external_source_events_source_event_id_unique" UNIQUE("source","source_event_id"),
	CONSTRAINT "external_source_events_type_allowed" CHECK ("external_source_events"."event_type" in ('settlement_credit', 'refund_debit')),
	CONSTRAINT "external_source_events_amount_positive" CHECK ("external_source_events"."amount_cents" > 0),
	CONSTRAINT "external_source_events_amount_safe_integer" CHECK ("external_source_events"."amount_cents" <= 9007199254740991),
	CONSTRAINT "external_source_events_currency_eur" CHECK ("external_source_events"."currency" = 'EUR'),
	CONSTRAINT "external_source_events_source_nonblank" CHECK (btrim("external_source_events"."source") <> ''),
	CONSTRAINT "external_source_events_source_event_id_nonblank" CHECK (btrim("external_source_events"."source_event_id") <> ''),
	CONSTRAINT "external_source_events_external_reference_nonblank" CHECK (btrim("external_source_events"."external_reference") <> ''),
	CONSTRAINT "external_source_events_provider_reference_nonblank" CHECK ("external_source_events"."provider_payment_reference" is null or btrim("external_source_events"."provider_payment_reference") <> ''),
	CONSTRAINT "external_source_events_raw_payload_size" CHECK (octet_length("external_source_events"."raw_payload") between 1 and 1048576),
	CONSTRAINT "external_source_events_metadata_object" CHECK (jsonb_typeof("external_source_events"."metadata") = 'object'),
	CONSTRAINT "external_source_events_metadata_size" CHECK (octet_length("external_source_events"."metadata"::text) <= 16384),
	CONSTRAINT "external_source_events_reference_consistency" CHECK ((
      ("external_source_events"."event_type" = 'settlement_credit' and "external_source_events"."internal_refund_id" is null)
      or ("external_source_events"."event_type" = 'refund_debit' and "external_source_events"."internal_payment_id" is null and "external_source_events"."provider_payment_reference" is null)
    ))
);
--> statement-breakpoint
CREATE TABLE "reconciliation_actions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "reconciliation_actions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"finding_id" integer NOT NULL,
	"action_type" varchar(16) NOT NULL,
	"from_status" varchar(16) NOT NULL,
	"to_status" varchar(16) NOT NULL,
	"actor_type" varchar(16) NOT NULL,
	"actor_id" varchar(128) NOT NULL,
	"reason" varchar(1000) NOT NULL,
	"idempotency_key" varchar(128) NOT NULL,
	"request_fingerprint" varchar(64) NOT NULL,
	"occurred_at" timestamp (3) with time zone NOT NULL,
	"recorded_at" timestamp (3) with time zone NOT NULL,
	CONSTRAINT "reconciliation_actions_finding_idempotency_unique" UNIQUE("finding_id","idempotency_key"),
	CONSTRAINT "reconciliation_actions_transition_allowed" CHECK ((
      ("reconciliation_actions"."action_type" = 'acknowledge' and "reconciliation_actions"."from_status" = 'open' and "reconciliation_actions"."to_status" = 'acknowledged')
      or ("reconciliation_actions"."action_type" = 'resolve' and "reconciliation_actions"."from_status" in ('open', 'acknowledged') and "reconciliation_actions"."to_status" = 'resolved')
      or ("reconciliation_actions"."action_type" = 'ignore' and "reconciliation_actions"."from_status" in ('open', 'acknowledged') and "reconciliation_actions"."to_status" = 'ignored')
    )),
	CONSTRAINT "reconciliation_actions_actor_operator" CHECK ("reconciliation_actions"."actor_type" = 'operator'),
	CONSTRAINT "reconciliation_actions_actor_id_nonblank" CHECK (btrim("reconciliation_actions"."actor_id") <> ''),
	CONSTRAINT "reconciliation_actions_reason_nonblank" CHECK (btrim("reconciliation_actions"."reason") <> ''),
	CONSTRAINT "reconciliation_actions_idempotency_key_format" CHECK ("reconciliation_actions"."idempotency_key" ~ '^[!-~]{1,128}$'),
	CONSTRAINT "reconciliation_actions_fingerprint_format" CHECK ("reconciliation_actions"."request_fingerprint" ~ '^[0-9a-f]{64}$')
);
--> statement-breakpoint
CREATE TABLE "reconciliation_finding_evidence" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "reconciliation_finding_evidence_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"finding_id" integer NOT NULL,
	"role" varchar(32) NOT NULL,
	"contract_id" integer,
	"installment_id" integer,
	"payment_id" integer,
	"refund_id" integer,
	"ledger_entry_id" integer,
	"stripe_webhook_event_id" integer,
	"external_source_event_id" integer,
	"created_at" timestamp (3) with time zone NOT NULL,
	CONSTRAINT "reconciliation_evidence_role_allowed" CHECK ("reconciliation_finding_evidence"."role" in ('subject', 'internal_fact', 'internal_effect', 'provider_evidence', 'external_evidence', 'contract_context')),
	CONSTRAINT "reconciliation_evidence_exactly_one_reference" CHECK (num_nonnulls("reconciliation_finding_evidence"."contract_id", "reconciliation_finding_evidence"."installment_id", "reconciliation_finding_evidence"."payment_id", "reconciliation_finding_evidence"."refund_id", "reconciliation_finding_evidence"."ledger_entry_id", "reconciliation_finding_evidence"."stripe_webhook_event_id", "reconciliation_finding_evidence"."external_source_event_id") = 1)
);
--> statement-breakpoint
CREATE TABLE "reconciliation_findings" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "reconciliation_findings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"run_id" integer NOT NULL,
	"rule_code" varchar(64) NOT NULL,
	"rule_version" integer NOT NULL,
	"severity" varchar(16) NOT NULL,
	"subject_type" varchar(32) NOT NULL,
	"subject_id" integer NOT NULL,
	"amount_delta_cents" bigint,
	"currency" varchar(3) NOT NULL,
	"status" varchar(16) NOT NULL,
	"fingerprint" varchar(64) NOT NULL,
	"created_at" timestamp (3) with time zone NOT NULL,
	"status_updated_at" timestamp (3) with time zone NOT NULL,
	CONSTRAINT "reconciliation_findings_run_fingerprint_unique" UNIQUE("run_id","fingerprint"),
	CONSTRAINT "reconciliation_findings_rule_allowed" CHECK ("reconciliation_findings"."rule_code" in ('STRIPE_SUCCESS_MISSING_INTERNAL_PAYMENT', 'INTERNAL_PAYMENT_MISSING_BANK_SETTLEMENT', 'BANK_SETTLEMENT_AMOUNT_MISMATCH', 'INTERNAL_REFUND_MISSING_BANK_OUTFLOW', 'ORPHAN_BANK_MOVEMENT')),
	CONSTRAINT "reconciliation_findings_rule_version_one" CHECK ("reconciliation_findings"."rule_version" = 1),
	CONSTRAINT "reconciliation_findings_severity_allowed" CHECK ("reconciliation_findings"."severity" in ('warning', 'critical')),
	CONSTRAINT "reconciliation_findings_subject_allowed" CHECK ("reconciliation_findings"."subject_type" in ('payment', 'refund', 'stripe_webhook_event', 'external_source_event')),
	CONSTRAINT "reconciliation_findings_rule_semantics" CHECK ((
      ("reconciliation_findings"."rule_code" = 'STRIPE_SUCCESS_MISSING_INTERNAL_PAYMENT' and "reconciliation_findings"."severity" = 'critical' and "reconciliation_findings"."subject_type" = 'stripe_webhook_event')
      or ("reconciliation_findings"."rule_code" = 'INTERNAL_PAYMENT_MISSING_BANK_SETTLEMENT' and "reconciliation_findings"."severity" = 'warning' and "reconciliation_findings"."subject_type" = 'payment')
      or ("reconciliation_findings"."rule_code" = 'BANK_SETTLEMENT_AMOUNT_MISMATCH' and "reconciliation_findings"."severity" = 'critical' and "reconciliation_findings"."subject_type" = 'payment')
      or ("reconciliation_findings"."rule_code" = 'INTERNAL_REFUND_MISSING_BANK_OUTFLOW' and "reconciliation_findings"."severity" = 'warning' and "reconciliation_findings"."subject_type" = 'refund')
      or ("reconciliation_findings"."rule_code" = 'ORPHAN_BANK_MOVEMENT' and "reconciliation_findings"."severity" = 'warning' and "reconciliation_findings"."subject_type" = 'external_source_event')
    )),
	CONSTRAINT "reconciliation_findings_subject_id_positive" CHECK ("reconciliation_findings"."subject_id" > 0),
	CONSTRAINT "reconciliation_findings_delta_safe_integer" CHECK ("reconciliation_findings"."amount_delta_cents" is null or "reconciliation_findings"."amount_delta_cents" between -9007199254740991 and 9007199254740991),
	CONSTRAINT "reconciliation_findings_currency_eur" CHECK ("reconciliation_findings"."currency" = 'EUR'),
	CONSTRAINT "reconciliation_findings_status_allowed" CHECK ("reconciliation_findings"."status" in ('open', 'acknowledged', 'resolved', 'ignored')),
	CONSTRAINT "reconciliation_findings_fingerprint_format" CHECK ("reconciliation_findings"."fingerprint" ~ '^[0-9a-f]{64}$')
);
--> statement-breakpoint
CREATE TABLE "reconciliation_runs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "reconciliation_runs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"scope_type" varchar(16) NOT NULL,
	"scope_id" integer,
	"cutoff" timestamp (3) with time zone NOT NULL,
	"rule_set_version" varchar(32) NOT NULL,
	"run_fingerprint" varchar(64) NOT NULL,
	"status" varchar(16) NOT NULL,
	"executed_at" timestamp (3) with time zone NOT NULL,
	"created_at" timestamp (3) with time zone NOT NULL,
	CONSTRAINT "reconciliation_runs_fingerprint_unique" UNIQUE("run_fingerprint"),
	CONSTRAINT "reconciliation_runs_global_scope" CHECK ("reconciliation_runs"."scope_type" = 'global' and "reconciliation_runs"."scope_id" is null),
	CONSTRAINT "reconciliation_runs_rule_set_v1" CHECK ("reconciliation_runs"."rule_set_version" = 'reconciliation-v1'),
	CONSTRAINT "reconciliation_runs_status_completed" CHECK ("reconciliation_runs"."status" = 'completed'),
	CONSTRAINT "reconciliation_runs_fingerprint_format" CHECK ("reconciliation_runs"."run_fingerprint" ~ '^[0-9a-f]{64}$')
);
--> statement-breakpoint
ALTER TABLE "idempotency_records" DROP CONSTRAINT "idempotency_records_command_type_allowed";--> statement-breakpoint
ALTER TABLE "external_source_events" ADD CONSTRAINT "external_source_events_payment_id_payments_id_fk" FOREIGN KEY ("internal_payment_id") REFERENCES "public"."payments"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "external_source_events" ADD CONSTRAINT "external_source_events_refund_id_refunds_id_fk" FOREIGN KEY ("internal_refund_id") REFERENCES "public"."refunds"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reconciliation_actions" ADD CONSTRAINT "reconciliation_actions_finding_id_findings_id_fk" FOREIGN KEY ("finding_id") REFERENCES "public"."reconciliation_findings"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reconciliation_finding_evidence" ADD CONSTRAINT "reconciliation_evidence_finding_id_findings_id_fk" FOREIGN KEY ("finding_id") REFERENCES "public"."reconciliation_findings"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reconciliation_finding_evidence" ADD CONSTRAINT "reconciliation_evidence_contract_id_contracts_id_fk" FOREIGN KEY ("contract_id") REFERENCES "public"."contracts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reconciliation_finding_evidence" ADD CONSTRAINT "reconciliation_evidence_installment_id_installments_id_fk" FOREIGN KEY ("installment_id") REFERENCES "public"."installments"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reconciliation_finding_evidence" ADD CONSTRAINT "reconciliation_evidence_payment_id_payments_id_fk" FOREIGN KEY ("payment_id") REFERENCES "public"."payments"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reconciliation_finding_evidence" ADD CONSTRAINT "reconciliation_evidence_refund_id_refunds_id_fk" FOREIGN KEY ("refund_id") REFERENCES "public"."refunds"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reconciliation_finding_evidence" ADD CONSTRAINT "reconciliation_evidence_ledger_id_ledger_entries_id_fk" FOREIGN KEY ("ledger_entry_id") REFERENCES "public"."ledger_entries"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reconciliation_finding_evidence" ADD CONSTRAINT "reconciliation_evidence_stripe_id_stripe_events_id_fk" FOREIGN KEY ("stripe_webhook_event_id") REFERENCES "public"."stripe_webhook_events"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reconciliation_finding_evidence" ADD CONSTRAINT "reconciliation_evidence_external_id_external_events_id_fk" FOREIGN KEY ("external_source_event_id") REFERENCES "public"."external_source_events"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "reconciliation_findings" ADD CONSTRAINT "reconciliation_findings_run_id_runs_id_fk" FOREIGN KEY ("run_id") REFERENCES "public"."reconciliation_runs"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "external_source_events_created_at_idx" ON "external_source_events" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "external_source_events_internal_payment_id_idx" ON "external_source_events" USING btree ("internal_payment_id");--> statement-breakpoint
CREATE INDEX "external_source_events_internal_refund_id_idx" ON "external_source_events" USING btree ("internal_refund_id");--> statement-breakpoint
CREATE INDEX "external_source_events_provider_payment_reference_idx" ON "external_source_events" USING btree ("provider_payment_reference");--> statement-breakpoint
CREATE INDEX "reconciliation_actions_finding_occurred_idx" ON "reconciliation_actions" USING btree ("finding_id","occurred_at","id");--> statement-breakpoint
CREATE UNIQUE INDEX "reconciliation_evidence_finding_contract_unique" ON "reconciliation_finding_evidence" USING btree ("finding_id","contract_id") WHERE "reconciliation_finding_evidence"."contract_id" is not null;--> statement-breakpoint
CREATE UNIQUE INDEX "reconciliation_evidence_finding_installment_unique" ON "reconciliation_finding_evidence" USING btree ("finding_id","installment_id") WHERE "reconciliation_finding_evidence"."installment_id" is not null;--> statement-breakpoint
CREATE UNIQUE INDEX "reconciliation_evidence_finding_payment_unique" ON "reconciliation_finding_evidence" USING btree ("finding_id","payment_id") WHERE "reconciliation_finding_evidence"."payment_id" is not null;--> statement-breakpoint
CREATE UNIQUE INDEX "reconciliation_evidence_finding_refund_unique" ON "reconciliation_finding_evidence" USING btree ("finding_id","refund_id") WHERE "reconciliation_finding_evidence"."refund_id" is not null;--> statement-breakpoint
CREATE UNIQUE INDEX "reconciliation_evidence_finding_ledger_unique" ON "reconciliation_finding_evidence" USING btree ("finding_id","ledger_entry_id") WHERE "reconciliation_finding_evidence"."ledger_entry_id" is not null;--> statement-breakpoint
CREATE UNIQUE INDEX "reconciliation_evidence_finding_stripe_unique" ON "reconciliation_finding_evidence" USING btree ("finding_id","stripe_webhook_event_id") WHERE "reconciliation_finding_evidence"."stripe_webhook_event_id" is not null;--> statement-breakpoint
CREATE UNIQUE INDEX "reconciliation_evidence_finding_external_unique" ON "reconciliation_finding_evidence" USING btree ("finding_id","external_source_event_id") WHERE "reconciliation_finding_evidence"."external_source_event_id" is not null;--> statement-breakpoint
CREATE INDEX "reconciliation_findings_run_severity_rule_idx" ON "reconciliation_findings" USING btree ("run_id","severity","rule_code");--> statement-breakpoint
CREATE INDEX "reconciliation_findings_status_severity_idx" ON "reconciliation_findings" USING btree ("status","severity");--> statement-breakpoint
CREATE INDEX "reconciliation_findings_subject_idx" ON "reconciliation_findings" USING btree ("subject_type","subject_id");--> statement-breakpoint
CREATE INDEX "reconciliation_runs_cutoff_idx" ON "reconciliation_runs" USING btree ("cutoff");--> statement-breakpoint
ALTER TABLE "idempotency_records" ADD CONSTRAINT "idempotency_records_command_type_allowed" CHECK ("idempotency_records"."command_type" in ('create_customer', 'create_contract', 'record_payment', 'record_refund', 'run_reconciliation', 'act_on_reconciliation_finding'));
--> statement-breakpoint
CREATE FUNCTION reject_reconciliation_immutable_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
	RAISE EXCEPTION '% is immutable', TG_TABLE_NAME;
END;
$$;
--> statement-breakpoint
CREATE TRIGGER external_source_events_immutable
BEFORE UPDATE OR DELETE ON "external_source_events"
FOR EACH ROW EXECUTE FUNCTION reject_reconciliation_immutable_mutation();
--> statement-breakpoint
CREATE TRIGGER reconciliation_runs_immutable
BEFORE UPDATE OR DELETE ON "reconciliation_runs"
FOR EACH ROW EXECUTE FUNCTION reject_reconciliation_immutable_mutation();
--> statement-breakpoint
CREATE TRIGGER reconciliation_finding_evidence_immutable
BEFORE UPDATE OR DELETE ON "reconciliation_finding_evidence"
FOR EACH ROW EXECUTE FUNCTION reject_reconciliation_immutable_mutation();
--> statement-breakpoint
CREATE TRIGGER reconciliation_actions_immutable
BEFORE UPDATE OR DELETE ON "reconciliation_actions"
FOR EACH ROW EXECUTE FUNCTION reject_reconciliation_immutable_mutation();
--> statement-breakpoint
CREATE FUNCTION protect_reconciliation_finding_history()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
	IF TG_OP = 'DELETE' THEN
		RAISE EXCEPTION 'reconciliation_findings cannot be deleted';
	END IF;

	IF OLD.id IS DISTINCT FROM NEW.id
		OR OLD.run_id IS DISTINCT FROM NEW.run_id
		OR OLD.rule_code IS DISTINCT FROM NEW.rule_code
		OR OLD.rule_version IS DISTINCT FROM NEW.rule_version
		OR OLD.severity IS DISTINCT FROM NEW.severity
		OR OLD.subject_type IS DISTINCT FROM NEW.subject_type
		OR OLD.subject_id IS DISTINCT FROM NEW.subject_id
		OR OLD.amount_delta_cents IS DISTINCT FROM NEW.amount_delta_cents
		OR OLD.currency IS DISTINCT FROM NEW.currency
		OR OLD.fingerprint IS DISTINCT FROM NEW.fingerprint
		OR OLD.created_at IS DISTINCT FROM NEW.created_at THEN
		RAISE EXCEPTION 'reconciliation_findings historical fields cannot be changed';
	END IF;

	RETURN NEW;
END;
$$;
--> statement-breakpoint
CREATE TRIGGER reconciliation_findings_protect_history
BEFORE UPDATE OR DELETE ON "reconciliation_findings"
FOR EACH ROW EXECUTE FUNCTION protect_reconciliation_finding_history();
