CREATE TABLE "audit_events" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "audit_events_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"action" varchar(64) NOT NULL,
	"actor_type" varchar(16) NOT NULL,
	"actor_id" varchar(255) NOT NULL,
	"resource_type" varchar(32) NOT NULL,
	"resource_id" integer NOT NULL,
	"outcome" varchar(16) NOT NULL,
	"reason" varchar(1000),
	"deduplication_key" varchar(64) NOT NULL,
	"recorded_at" timestamp (3) with time zone NOT NULL,
	CONSTRAINT "audit_events_deduplication_key_unique" UNIQUE("deduplication_key"),
	CONSTRAINT "audit_events_id_positive" CHECK ("audit_events"."id">0),
	CONSTRAINT "audit_events_action_allowed" CHECK ("audit_events"."action" in ('customer.create','contract.create','payment.record','refund.record','external_source_event.record','reconciliation.run','reconciliation.finding.acknowledge','reconciliation.finding.resolve','reconciliation.finding.ignore')),
	CONSTRAINT "audit_events_actor_user" CHECK ("audit_events"."actor_type"='user'),
	CONSTRAINT "audit_events_actor_nonblank" CHECK (btrim("audit_events"."actor_id")<>''),
	CONSTRAINT "audit_events_resource_type_allowed" CHECK ("audit_events"."resource_type" in ('customer','contract','payment','refund','external_source_event','reconciliation_run','reconciliation_finding')),
	CONSTRAINT "audit_events_resource_id_positive" CHECK ("audit_events"."resource_id">0),
	CONSTRAINT "audit_events_outcome_allowed" CHECK ("audit_events"."outcome" in ('created','replayed')),
	CONSTRAINT "audit_events_reason_valid" CHECK ("audit_events"."reason" is null or btrim("audit_events"."reason")<>''),
	CONSTRAINT "audit_events_deduplication_key_format" CHECK ("audit_events"."deduplication_key" ~ '^[0-9a-f]{64}$')
);
--> statement-breakpoint
CREATE FUNCTION reject_audit_event_mutation()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
	RAISE EXCEPTION 'audit_events is append-only';
END;
$$;
--> statement-breakpoint
CREATE TRIGGER audit_events_append_only
BEFORE UPDATE OR DELETE ON "audit_events"
FOR EACH ROW EXECUTE FUNCTION reject_audit_event_mutation();
