import { PostgreSqlContainer, type StartedPostgreSqlContainer } from "@testcontainers/postgresql";
import { sql } from "drizzle-orm";
import { migrate } from "drizzle-orm/node-postgres/migrator";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { DEMO_PERIOD, seedDemoDataset, type DemoDatasetResult } from "../../../src/demo/demo-dataset.js";
import { resetKnownDemoTables } from "../../../src/demo/reset-demo.js";
import { createDatabase, type Database } from "../../../src/persistence/database.js";
import { getContractFinancialTimelineV1, getFinancialSummaryV1, getReconciliationSummaryV1 } from "../../../src/analytics/application/analytics-queries.js";
import { PostgresAnalyticsQueries } from "../../../src/analytics/persistence/postgres-analytics-queries.js";

describe.sequential("Analytics v1 PostgreSQL queries", () => {
  let container: StartedPostgreSqlContainer; let database: Database; let demo: DemoDatasetResult; let queries: PostgresAnalyticsQueries;
  beforeAll(async () => { container=await new PostgreSqlContainer("postgres:18.4").withDatabase("rios_demo").start(); database=createDatabase({connectionString:container.getConnectionUri()}); await migrate(database.client,{migrationsFolder:"./drizzle"}); await resetKnownDemoTables(database); demo=await seedDemoDataset(database); queries=new PostgresAnalyticsQueries(database); },120_000);
  afterAll(async()=>{await database?.close();await container?.stop();},30_000);
  it("returns every golden metric without join multiplication", async()=>{ const summary=await getFinancialSummaryV1(queries)(DEMO_PERIOD); expect(summary).toMatchObject({contractedCents:27000,scheduledDueCents:27000,grossRecordedPaymentsCents:19000,refundsCents:3000,netRecordedPaymentsCents:16000,bankSettledGrossCents:15500,bankRefundOutflowsCents:3000,bankSettledNetCents:12500,outstandingExposureCents:11000,overdueExposureCents:11000}); });
  it("honors half-open event and due-date boundaries", async()=>{ const summary=await getFinancialSummaryV1(queries)({periodStart:new Date("2026-06-10T00:00:00Z"),periodEnd:new Date("2026-06-20T11:00:00Z"),asOf:DEMO_PERIOD.asOf}); expect(summary).toMatchObject({scheduledDueCents:3000,grossRecordedPaymentsCents:4000,refundsCents:3000,netRecordedPaymentsCents:1000}); });
  it("returns a stable Contract timeline", async()=>{ const timeline=await getContractFinancialTimelineV1(queries)({contractId:demo.contractIds[0],asOf:DEMO_PERIOD.asOf}); expect(timeline.events.map((event)=>event.type)).toEqual(["installment_due","payment_recorded","stripe_evidence","external_settlement_credit","refund_recorded","external_refund_debit","payment_recorded","installment_due","installment_due"]); });
  it("reconstructs status by recorded knowledge time and zero-fills dimensions", async()=>{ const before=await getReconciliationSummaryV1(queries)({runId:demo.runId,statusAsOf:new Date("2026-09-01T08:59:59Z")}); expect(before.byStatus).toEqual({open:3,acknowledged:0,resolved:0,ignored:0}); const final=await getReconciliationSummaryV1(queries)({runId:demo.runId,statusAsOf:DEMO_PERIOD.statusAsOf}); expect(final).toMatchObject({totalFindings:3,openFindings:1,bySeverity:{warning:2,critical:1},byStatus:{open:1,acknowledged:0,resolved:1,ignored:1}}); expect(final.byRule).toEqual({STRIPE_SUCCESS_MISSING_INTERNAL_PAYMENT:0,INTERNAL_PAYMENT_MISSING_BANK_SETTLEMENT:1,BANK_SETTLEMENT_AMOUNT_MISMATCH:1,INTERNAL_REFUND_MISSING_BANK_OUTFLOW:0,ORPHAN_BANK_MOVEMENT:1}); });
  it("excludes backdated bank evidence learned after asOf", async()=>{ await database.client.execute(sql`insert into external_source_events(source,source_event_id,event_type,amount_cents,currency,occurred_at,received_at,external_reference,internal_payment_id,raw_payload,metadata,created_at) values('simulated_demo_bank','late-knowledge','settlement_credit',3000,'EUR','2026-06-21','2026-09-03','late',${demo.paymentIds[1]},'{}','{}','2026-09-03')`); const summary=await getFinancialSummaryV1(queries)(DEMO_PERIOD); expect(summary.bankSettledGrossCents).toBe(15500); });
  it("does not mark due-today exposure overdue", async()=>{ await database.client.execute(sql`insert into customers(id,display_name,created_at) values(99,'Boundary','2026-08-01'); insert into contracts(id,customer_id,total_amount_cents,currency,installment_count,first_due_date,status,created_at) values(99,99,100,'EUR',1,'2026-09-02','active','2026-08-01'); insert into installments(id,contract_id,position,amount_cents,due_date,status,created_at) values(99,99,1,100,'2026-09-02','pending','2026-08-01')`); const summary=await getFinancialSummaryV1(queries)({...DEMO_PERIOD,contractId:99}); expect(summary).toMatchObject({outstandingExposureCents:100,overdueExposureCents:0}); });
});
