import { PostgreSqlContainer, type StartedPostgreSqlContainer } from "@testcontainers/postgresql";
import { sql } from "drizzle-orm";
import { migrate } from "drizzle-orm/node-postgres/migrator";
import { afterAll, beforeAll, beforeEach, describe, expect, it } from "vitest";
import { IdempotencyPayloadConflict } from "../../../src/application/idempotency.js";
import { createDatabase, type Database } from "../../../src/persistence/database.js";
import { runReconciliationUseCase } from "../../../src/reconciliation/application/run-reconciliation.js";
import { PostgresReconciliationPersistence } from "../../../src/reconciliation/persistence/postgres-reconciliation-persistence.js";

const CUTOFF = new Date("2026-09-02T12:00:00Z");
describe.sequential("Atomic reconciliation runs", () => {
  let container: StartedPostgreSqlContainer; let database: Database;
  beforeAll(async () => { container = await new PostgreSqlContainer("postgres:18.4").start(); database = createDatabase({ connectionString: container.getConnectionUri() }); await migrate(database.client, { migrationsFolder: "./drizzle" }); }, 120_000);
  beforeEach(() => database.client.execute(sql`truncate reconciliation_actions, reconciliation_finding_evidence, reconciliation_findings, reconciliation_runs, external_source_events, stripe_webhook_events, ledger_entries, refund_allocations, refunds, payment_allocations, payments, installments, contracts, idempotency_records, customers restart identity cascade`));
  afterAll(async () => { await database?.close(); await container?.stop(); }, 30_000);
  const useCase = (persistence = new PostgresReconciliationPersistence(database)) => runReconciliationUseCase({ clock: { now: () => new Date("2026-09-02T13:00:00Z") }, persistence });
  async function seedFiveRules() {
    await database.client.execute(sql`insert into customers(id,display_name,created_at) values(1,'Customer','2026-09-01'); insert into contracts(id,customer_id,total_amount_cents,currency,installment_count,first_due_date,status,created_at) values(1,1,30000,'EUR',1,'2026-09-01','active','2026-09-01'); insert into installments(id,contract_id,position,amount_cents,due_date,status,created_at) values(1,1,1,30000,'2026-09-01','partially_paid','2026-09-01'); insert into payments(id,contract_id,amount_cents,received_at,created_at) values(1,1,10000,'2026-09-01','2026-09-01'),(2,1,10000,'2026-09-01','2026-09-01'); insert into refunds(id,payment_id,amount_cents,refunded_at,created_at) values(1,1,1000,'2026-09-01','2026-09-01'); insert into ledger_entries(id,payment_id,effect_type,amount_cents,currency,event_at,recorded_at) values(1,1,'payment_recorded',10000,'EUR','2026-09-01','2026-09-01'),(2,2,'payment_recorded',10000,'EUR','2026-09-01','2026-09-01'); insert into ledger_entries(id,refund_id,effect_type,amount_cents,currency,event_at,recorded_at) values(3,1,'refund_recorded',1000,'EUR','2026-09-01','2026-09-01'); insert into stripe_webhook_events(id,stripe_event_id,event_type,stripe_payment_intent_id,raw_payload,received_at,status,processed_at,last_error_code) values(1,'evt_unlinked','payment_intent.succeeded','pi_unlinked','{}','2026-09-01','failed','2026-09-01','INVALID_CONTRACT_MAPPING'); insert into external_source_events(id,source,source_event_id,event_type,amount_cents,currency,occurred_at,received_at,external_reference,internal_payment_id,raw_payload,metadata,created_at) values(1,'simulated_bank','bank-mismatch','settlement_credit',9500,'EUR','2026-09-01','2026-09-01','ref-1',2,'{}','{}','2026-09-01'),(2,'simulated_bank','bank-orphan','settlement_credit',500,'EUR','2026-09-01','2026-09-01','ref-2',null,'{}','{}','2026-09-01')`);
  }
  it("persists a fully empty reconciled Run atomically", async () => { const result = await useCase()({ idempotencyKey: "run-empty", cutoff: CUTOFF }); expect(result.outcome).toBe("created"); expect(await new PostgresReconciliationPersistence(database).listFindings({ runId: result.resource.id, limit: 100 })).toEqual([]); });
  it("persists all five rule classes with typed Evidence", async () => { await seedFiveRules(); const persistence = new PostgresReconciliationPersistence(database); const result = await useCase(persistence)({ idempotencyKey: "run-five", cutoff: CUTOFF }); const findings = await persistence.listFindings({ runId: result.resource.id, limit: 100 }); expect(new Set(findings.map((finding) => finding.ruleCode))).toEqual(new Set(["STRIPE_SUCCESS_MISSING_INTERNAL_PAYMENT","INTERNAL_PAYMENT_MISSING_BANK_SETTLEMENT","BANK_SETTLEMENT_AMOUNT_MISMATCH","INTERNAL_REFUND_MISSING_BANK_OUTFLOW","ORPHAN_BANK_MOVEMENT"])); for (const finding of findings) expect((await persistence.getFindingById(finding.id))!.evidence.length).toBeGreaterThan(0); });
  it("replays the same key and rejects a changed cutoff", async () => { const run = useCase(); const first = await run({ idempotencyKey: "same-key", cutoff: CUTOFF }); expect((await run({ idempotencyKey: "same-key", cutoff: CUTOFF })).resource.id).toBe(first.resource.id); await expect(run({ idempotencyKey: "same-key", cutoff: new Date(CUTOFF.getTime() + 1) })).rejects.toThrow(IdempotencyPayloadConflict); });
  it("converges concurrent different keys for one logical Run", async () => { const run = useCase(); const results = await Promise.all([run({ idempotencyKey: "concurrent-a", cutoff: CUTOFF }), run({ idempotencyKey: "concurrent-b", cutoff: CUTOFF })]); expect(results[0].resource.id).toBe(results[1].resource.id); const count = await database.client.execute(sql`select count(*)::int as count from reconciliation_runs`); expect(count.rows[0]).toEqual({ count: 1 }); });
  it("uses createdAt, not occurredAt, for late-arriving external evidence", async () => { await seedFiveRules(); await database.client.execute(sql`insert into external_source_events(id,source,source_event_id,event_type,amount_cents,currency,occurred_at,received_at,external_reference,internal_payment_id,raw_payload,metadata,created_at) values(3,'simulated_bank','late','settlement_credit',10000,'EUR','2026-08-01','2026-09-03','late',1,'{}','{}','2026-09-03')`); const persistence = new PostgresReconciliationPersistence(database); const early = await useCase(persistence)({ idempotencyKey: "early", cutoff: new Date("2026-09-02") }); expect((await persistence.listFindings({ runId: early.resource.id, ruleCode: "INTERNAL_PAYMENT_MISSING_BANK_SETTLEMENT", limit: 100 })).some((finding) => finding.subjectId === 1)).toBe(true); const late = await useCase(persistence)({ idempotencyKey: "late", cutoff: new Date("2026-09-03T23:59:59Z") }); expect((await persistence.listFindings({ runId: late.resource.id, ruleCode: "INTERNAL_PAYMENT_MISSING_BANK_SETTLEMENT", limit: 100 })).some((finding) => finding.subjectId === 1)).toBe(false); });
  it("hides a Stripe Payment link until processedAt", async () => { await seedFiveRules(); await database.client.execute(sql`insert into stripe_webhook_events(id,stripe_event_id,event_type,stripe_payment_intent_id,raw_payload,received_at,status,processed_at,payment_id) values(2,'evt_latelink','payment_intent.succeeded','pi_latelink','{}','2026-09-01','processed','2026-09-03',1); insert into external_source_events(id,source,source_event_id,event_type,amount_cents,currency,occurred_at,received_at,external_reference,provider_payment_reference,raw_payload,metadata,created_at) values(3,'simulated_bank','provider-linked','settlement_credit',10000,'EUR','2026-09-01','2026-09-01','provider','pi_latelink','{}','{}','2026-09-01')`); const persistence = new PostgresReconciliationPersistence(database); const early = await useCase(persistence)({ idempotencyKey: "stripe-early", cutoff: new Date("2026-09-02") }); expect((await persistence.listFindings({ runId: early.resource.id, ruleCode: "STRIPE_SUCCESS_MISSING_INTERNAL_PAYMENT", limit: 100 })).some((finding) => finding.subjectId === 2)).toBe(true); const late = await useCase(persistence)({ idempotencyKey: "stripe-late", cutoff: new Date("2026-09-04") }); expect((await persistence.listFindings({ runId: late.resource.id, ruleCode: "STRIPE_SUCCESS_MISSING_INTERNAL_PAYMENT", limit: 100 })).some((finding) => finding.subjectId === 2)).toBe(false); expect((await persistence.listFindings({ runId: late.resource.id, ruleCode: "INTERNAL_PAYMENT_MISSING_BANK_SETTLEMENT", limit: 100 })).some((finding) => finding.subjectId === 1)).toBe(false); });
  it("rolls back Run, Finding, Evidence, and idempotency after injected failure", async () => { await seedFiveRules(); const failing = new PostgresReconciliationPersistence(database, (stage) => { if (stage === "evidence") throw new Error("injected"); }); await expect(useCase(failing)({ idempotencyKey: "rollback", cutoff: CUTOFF })).rejects.toThrow("injected"); for (const table of ["reconciliation_runs","reconciliation_findings","reconciliation_finding_evidence","idempotency_records"]) { const result = await database.client.execute(sql.raw(`select count(*)::int as count from ${table}`)); expect(result.rows[0]).toEqual({ count: 0 }); } });
});
