import { PostgreSqlContainer, type StartedPostgreSqlContainer } from "@testcontainers/postgresql";
import { sql } from "drizzle-orm";
import { migrate } from "drizzle-orm/node-postgres/migrator";
import { afterAll, beforeAll, beforeEach, describe, expect, it } from "vitest";
import { IdempotencyPayloadConflict } from "../../../src/application/idempotency.js";
import { createDatabase, type Database } from "../../../src/persistence/database.js";
import { actOnReconciliationFindingUseCase } from "../../../src/reconciliation/application/act-on-reconciliation-finding.js";
import { IllegalReconciliationTransition } from "../../../src/reconciliation/application/reconciliation-action-persistence.js";
import { PostgresReconciliationActionPersistence } from "../../../src/reconciliation/persistence/postgres-reconciliation-action-persistence.js";
import { PostgresReconciliationPersistence } from "../../../src/reconciliation/persistence/postgres-reconciliation-persistence.js";
const AT = new Date("2026-09-02T10:00:00Z"); let serial = 0;
describe.sequential("Reconciliation Finding lifecycle", () => {
  let container: StartedPostgreSqlContainer; let database: Database;
  beforeAll(async () => { container = await new PostgreSqlContainer("postgres:18.4").start(); database = createDatabase({ connectionString: container.getConnectionUri() }); await migrate(database.client, { migrationsFolder: "./drizzle" }); }, 120_000);
  beforeEach(() => database.client.execute(sql`truncate reconciliation_actions, reconciliation_finding_evidence, reconciliation_findings, reconciliation_runs, idempotency_records restart identity cascade`));
  afterAll(async () => { await database?.close(); await container?.stop(); }, 30_000);
  async function finding(status = "open") { serial += 1; const run = await database.client.execute<{ id: number }>(sql`insert into reconciliation_runs(scope_type,scope_id,cutoff,rule_set_version,run_fingerprint,status,executed_at,created_at) values('global',null,${AT},'reconciliation-v1',${serial.toString(16).padStart(64,"0")},'completed',${AT},${AT}) returning id`); const result = await database.client.execute<{ id: number }>(sql`insert into reconciliation_findings(run_id,rule_code,rule_version,severity,subject_type,subject_id,currency,status,fingerprint,created_at,status_updated_at) values(${run.rows[0]!.id},'ORPHAN_BANK_MOVEMENT',1,'warning','external_source_event',1,'EUR',${status},${(serial+1000).toString(16).padStart(64,"0")},${AT},${AT}) returning id`); return result.rows[0]!.id; }
  const useCase = (p = new PostgresReconciliationActionPersistence(database)) => actOnReconciliationFindingUseCase({ clock: { now: () => new Date(AT) }, persistence: p });
  const command = (findingId: number, actionType: "acknowledge"|"resolve"|"ignore", key = `${actionType}-${findingId}`) => ({ idempotencyKey: key, findingId, actionType, actorId: "demo-operator", reason: "Evidence reviewed", occurredAt: new Date(AT) });
  it("supports every allowed transition", async () => { for (const [start, first, second] of [["open","acknowledge",null],["open","resolve",null],["open","ignore",null],["open","acknowledge","resolve"],["open","acknowledge","ignore"]] as const) { const id = await finding(start); const run = useCase(); await run(command(id, first, `${first}-${id}-a`)); if (second) await run(command(id, second, `${second}-${id}-b`)); const read = await new PostgresReconciliationPersistence(database).getFindingById(id); expect(read!.finding.status).toBe(second === "resolve" ? "resolved" : second === "ignore" ? "ignored" : first === "acknowledge" ? "acknowledged" : first === "resolve" ? "resolved" : "ignored"); } });
  it("rejects terminal transitions", async () => { const id = await finding(); const run = useCase(); await run(command(id,"resolve")); await expect(run(command(id,"ignore","later"))).rejects.toThrow(IllegalReconciliationTransition); });
  it("replays same payload and conflicts changed payload", async () => { const id = await finding(); const run = useCase(); const first = await run(command(id,"resolve","same")); expect((await run(command(id,"resolve","same"))).resource.id).toBe(first.resource.id); await expect(run({ ...command(id,"resolve","same"), reason: "Different" })).rejects.toThrow(IdempotencyPayloadConflict); });
  it("serializes concurrent identical and incompatible actions", async () => { let id = await finding(); let results = await Promise.all([useCase()(command(id,"resolve","same-race")), useCase()(command(id,"resolve","same-race"))]); expect(results[0].resource.id).toBe(results[1].resource.id); id = await finding(); const competing = await Promise.allSettled([useCase()(command(id,"resolve","resolve-race")), useCase()(command(id,"ignore","ignore-race"))]); expect(competing.filter((result) => result.status === "fulfilled")).toHaveLength(1); expect(competing.filter((result) => result.status === "rejected" && result.reason instanceof IllegalReconciliationTransition)).toHaveLength(1); });
  it("preserves a legal serial order for acknowledge versus resolve", async () => { const id = await finding(); const results = await Promise.allSettled([useCase()(command(id,"acknowledge","ack-race")), useCase()(command(id,"resolve","resolve-race"))]); const read = await new PostgresReconciliationPersistence(database).getFindingById(id); expect(["resolved"]).toContain(read!.finding.status); expect(read!.actions.map((action) => action.toStatus)).toEqual(results.every((result) => result.status === "fulfilled") ? ["acknowledged","resolved"] : ["resolved"]); });
  it("rolls back Action, projection and idempotency on failure", async () => { const id = await finding(); await expect(useCase(new PostgresReconciliationActionPersistence(database, () => { throw new Error("injected"); }))(command(id,"resolve","rollback"))).rejects.toThrow("injected"); const read = await new PostgresReconciliationPersistence(database).getFindingById(id); expect(read!.finding.status).toBe("open"); expect(read!.actions).toEqual([]); const records = await database.client.execute(sql`select count(*)::int as count from idempotency_records`); expect(records.rows[0]).toEqual({ count: 0 }); });
});
