import { validateApplicationInput } from "../../application/input-validation.js";
import { DomainValidationError } from "../../domain/domain-validation-error.js";

export const ANALYTICS_VERSION = "analytics-v1" as const;
export interface FinancialSummaryV1 { readonly version: typeof ANALYTICS_VERSION; readonly currency: "EUR"; readonly periodStart: Date; readonly periodEnd: Date; readonly asOf: Date; readonly contractedCents: number; readonly scheduledDueCents: number; readonly grossRecordedPaymentsCents: number; readonly refundsCents: number; readonly netRecordedPaymentsCents: number; readonly bankSettledGrossCents: number; readonly bankRefundOutflowsCents: number; readonly bankSettledNetCents: number; readonly outstandingExposureCents: number; readonly overdueExposureCents: number; }
export type TimelineEventType = "installment_due" | "payment_recorded" | "refund_recorded" | "stripe_evidence" | "external_settlement_credit" | "external_refund_debit";
export interface ContractTimelineEventV1 { readonly type: TimelineEventType; readonly entityId: number; readonly effectiveAt: string; readonly amountCents: number | null; }
export interface ContractFinancialTimelineV1 { readonly version: typeof ANALYTICS_VERSION; readonly currency: "EUR"; readonly contractId: number; readonly customerId: number; readonly totalAmountCents: number; readonly asOf: Date; readonly events: ReadonlyArray<ContractTimelineEventV1>; }
export interface ReconciliationSummaryV1 { readonly version: typeof ANALYTICS_VERSION; readonly runId: number; readonly cutoff: Date; readonly ruleSetVersion: "reconciliation-v1"; readonly statusAsOf: Date; readonly totalFindings: number; readonly openFindings: number; readonly byRule: Readonly<Record<string, number>>; readonly bySeverity: Readonly<Record<string, number>>; readonly byStatus: Readonly<Record<string, number>>; }
export interface FinancialSummaryInput { readonly periodStart: Date; readonly periodEnd: Date; readonly asOf: Date; readonly customerId?: number; readonly contractId?: number; }
export interface ContractTimelineInput { readonly contractId: number; readonly asOf: Date; readonly periodStart?: Date; readonly periodEnd?: Date; }
export interface ReconciliationSummaryInput { readonly runId: number; readonly statusAsOf: Date; }
export interface AnalyticsQueryPersistence { getFinancialSummaryV1(input: FinancialSummaryInput): Promise<FinancialSummaryV1>; getContractFinancialTimelineV1(input: ContractTimelineInput): Promise<ContractFinancialTimelineV1 | null>; getReconciliationSummaryV1(input: ReconciliationSummaryInput): Promise<ReconciliationSummaryV1 | null>; }
export class AnalyticsContractNotFoundError extends Error { override readonly name = "AnalyticsContractNotFoundError"; constructor(readonly contractId: number) { super(`Contract ${contractId} was not found`); } }
export class AnalyticsRunNotFoundError extends Error { override readonly name = "AnalyticsRunNotFoundError"; constructor(readonly runId: number) { super(`Reconciliation Run ${runId} was not found`); } }

function instant(value: Date, label: string): Date { if (!(value instanceof Date) || Number.isNaN(value.getTime())) throw new DomainValidationError("INVALID_ANALYTICS_INSTANT", `${label} must be a valid instant`); return new Date(value); }
function id(value: number, label: string): number { if (!Number.isSafeInteger(value) || value < 1) throw new DomainValidationError("INVALID_ID", `${label} must be a positive safe integer`); return value; }
function period(input: FinancialSummaryInput) { const periodStart = instant(input.periodStart, "periodStart"); const periodEnd = instant(input.periodEnd, "periodEnd"); const asOf = instant(input.asOf, "asOf"); if (periodStart >= periodEnd || asOf < periodStart) throw new DomainValidationError("INVALID_ANALYTICS_PERIOD", "Analytics period must be half-open and asOf must not precede periodStart"); return { periodStart, periodEnd, asOf, ...(input.customerId === undefined ? {} : { customerId: id(input.customerId, "customerId") }), ...(input.contractId === undefined ? {} : { contractId: id(input.contractId, "contractId") }) }; }
export function getFinancialSummaryV1(persistence: AnalyticsQueryPersistence) { return (input: FinancialSummaryInput) => persistence.getFinancialSummaryV1(validateApplicationInput(() => period(input))); }
export function getContractFinancialTimelineV1(persistence: AnalyticsQueryPersistence) { return async (input: ContractTimelineInput) => { const validated = validateApplicationInput(() => { const asOf = instant(input.asOf, "asOf"); const periodStart = input.periodStart === undefined ? undefined : instant(input.periodStart, "periodStart"); const periodEnd = input.periodEnd === undefined ? undefined : instant(input.periodEnd, "periodEnd"); if ((periodStart === undefined) !== (periodEnd === undefined) || (periodStart && periodEnd && periodStart >= periodEnd)) throw new DomainValidationError("INVALID_ANALYTICS_PERIOD", "Timeline period bounds must be paired and half-open"); return { contractId: id(input.contractId, "contractId"), asOf, ...(periodStart ? { periodStart } : {}), ...(periodEnd ? { periodEnd } : {}) }; }); const result = await persistence.getContractFinancialTimelineV1(validated); if (!result) throw new AnalyticsContractNotFoundError(validated.contractId); return result; }; }
export function getReconciliationSummaryV1(persistence: AnalyticsQueryPersistence) { return async (input: ReconciliationSummaryInput) => { const validated = validateApplicationInput(() => ({ runId: id(input.runId, "runId"), statusAsOf: instant(input.statusAsOf, "statusAsOf") })); const result = await persistence.getReconciliationSummaryV1(validated); if (!result) throw new AnalyticsRunNotFoundError(validated.runId); return result; }; }
